import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "AI Blog Summarizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="{`${poppins.variable} ${roboto.variable}`}">
      <body
      >
        <main className="bg-purple-950">
          {children}
        </main>
      </body>
    </html>
  );
}
